DigitecGalaxus/next-yak

packages/next-yak/loaders/cssloader.cjs, packages/next-yak/loaders/tsloader.cjs, packages/next-yak/runtime/styled.tsx
right now our loaders randomly pick up babel configs which might cause unexpected behaviour
=> ignore babelrc

packages/next-yak/loaders/__tests__/tsloader.test.ts, packages/next-yak/loaders/babel-yak-plugin.cjs, packages/next-yak/loaders/babel-yak-plugin.d.ts, packages/next-yak/loaders/tsloader.cjs, packages/next-yak/package.json
moving the babel plugin into a stand alone plugin allows to use it for jest.
right now it would NOT work as jest plugin because it is 1:1 version of the previous implementation.
to be useful in a jest / vite environment the plugin would require a flag which would:
- not inejct the import
- would not use the injected import but rather a string like "yak-styles"
we should also add a test in our example package
=> move babel plugin to separate file

packages/next-yak/runtime/__tests__/styled.test.tsx, packages/next-yak/runtime/cssLiteral.tsx
this fixes an issue where returning `null` would throw an exception
=> support null values

packages/next-yak/loaders/__tests__/classifier.test.ts, packages/next-yak/loaders/__tests__/tsloader.test.ts, packages/next-yak/loaders/babel-yak-plugin.cjs, packages/next-yak/loaders/cssloader.cjs, packages/next-yak/loaders/lib/getStyledComponentName.cjs, packages/next-yak/loaders/lib/getYakImports.cjs, packages/next-yak/loaders/lib/quasiClassifier.cjs, packages/next-yak/loaders/lib/replaceQuasiExpressionTokens.cjs, packages/next-yak/loaders/lib/stripCssComments.cjs, packages/next-yak/loaders/tsloader.cjs, packages/next-yak/package.json
adds meaningful errors for nested css mixins (see #40 )
=> show error messages for nested mixins which can not be extracted

packages/next-yak/README.md, packages/next-yak/loaders/__tests__/tsloader.test.ts, packages/next-yak/loaders/babel-yak-plugin.cjs, packages/next-yak/package.json
This PR detects very simple error cases:
```js
styled.button`
&:focus { ${myMixn} }
`
```
it detects the mistake by checking if the expression is a variable
This will not detect errors from inlined arrow functions:
```js
styled.button`
&:focus { ${() => myMixn} }
`
```
=> add error messages for simple cases

packages/next-yak/loaders/__tests__/cssloader.test.ts, packages/next-yak/loaders/__tests__/getCssName.test.ts, packages/next-yak/loaders/__tests__/tsloader.test.ts, packages/next-yak/loaders/babel-yak-plugin.cjs, packages/next-yak/loaders/cssloader.cjs, packages/next-yak/loaders/lib/getCssName.cjs, packages/next-yak/loaders/lib/localIdent.cjs, packages/next-yak/package.json
=> better css class names

packages/next-yak/loaders/__tests__/cssloader.test.ts, packages/next-yak/loaders/lib/replaceQuasiExpressionTokens.cjs, packages/next-yak/package.json
we got a request to support numeric indexes for yak files e.g.:
```ts
import { spacings } from "./constants.yak";
const Button = styled.button`
margin: ${spacings[0]}
`
```
this pr uses recursions to allow any combination of computed and uncomputed member expressions like for example:
`a.usage["of"][5].member.expressions`
=> add square-bracket-support

packages/docs/package.json, pnpm-lock.yaml
Adds building of `next-yak` the first step of building the docs package.
This ensures that the docs & playground have the latest version of `next-yak` in their bundle
=> Build next-yak when building the docs

packages/next-yak/package.json, packages/next-yak/runtime/__tests__/typeTest.tsx, packages/next-yak/runtime/cssLiteral.tsx, packages/next-yak/runtime/styled.tsx, pnpm-lock.yaml
Fixes #72 
Use `NoInfer<T>` in order to be explicit for the tagged template literal types and not inferring them from the functions that are used for dynamic props or child components.
Added bonus: The destructuring of the props in the tagged template literal gives you now type hints, as TypeScript doesn't want to infer it dynamically and the type is known when you start with the literal.
=> Fix composition types

package.json, packages/next-yak/package.json, packages/webpack-tests/README.md, packages/webpack-tests/__tests__/utils/comment-loader.js, packages/webpack-tests/__tests__/utils/testCompiler.ts, packages/webpack-tests/__tests__/yak.test.ts, packages/webpack-tests/package.json, packages/webpack-tests/vitest.config.ts, pnpm-lock.yaml
This PR introduces a new private package for the next-yak monorepository
It is called `webpack-tests` and is meant to test the integration into webpack for our bundling process
Key additions and improvements:
1. New `packages/webpack-tests` directory with comprehensive Webpack integration tests
2. Custom compilation function that simulates Next.js Webpack configuration and build process
3. In-memory file system setup for efficient and isolated testing
4. Tests to verify correct CSS extraction from TypeScript files using our custom loaders
5. Integration of `next-yak/withYak` into the build process (allows to test different configs)
6. Will allow us to run babel and swc tests with the same unit tests
The new test suite runs as part of our CI pipeline, adding an extra layer of confidence to …
=> add bundler integration tests for webpack

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/tests/fixture/cross-file/output.tsx
Comments are attached to `BytePos`, so you should not replace the span of the node with `DUMMY_SP` afterwards
=> Fix comments issue

.github/workflows/example.yml
this is in preparation for rust where we can't use the default vercel integration anymore
the reason is that vercel does not support rust in build pipelines but github does
=> add workflow for example

packages/next-yak/runtime/__tests__/attrs.test.tsx, packages/next-yak/runtime/__tests__/styled.test.tsx, packages/next-yak/runtime/styled.tsx
this improvement helps with snapshot results
=> ignore empty class names

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/tests/fixture/css-mixin-inline/input.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin-inline/output.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin-inline/skip
Allows to inline css literals like for example:
```ts
export const ThemedButton = styled.button`
${css`..`}
}
`;
```
Inlined css literals are actually not very useful but the logic behind that feature helps to inline constants in #149
=> allow inlining css expressions

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/src/naming_convention.rs, packages/yak-swc/yak_swc/src/utils/ast_helper.rs, packages/yak-swc/yak_swc/src/variable_visitor.rs, packages/yak-swc/yak_swc/src/yak_imports.rs, packages/yak-swc/yak_swc/src/yak_transforms.rs, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/input.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-object/input.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-object/output.tsx
This pull request addresses issue #166, where keyframe animations defined after their usage in styled components cause an "Unsupported template literal in css expression" error. The solution involves the following key changes:
- Introduced `ScopedVariableReference` to manage JavaScript variable references more effectively, ensuring that both simple and complex references (e.g., `foo` and `foo.bar`) are handled consistently
- Updated the handling of keyframe animations and nested CSS expressions to resolve references correctly, even when keyframes are defined after their usage
The solution is to link keyframe references with its declaration even before it was declared and reuse this name later during the actual declaration. This ensures that animations work seamlessly regardless of their …
=> fix keyframes order

packages/next-yak/package.json, packages/yak-swc/package.json, packages/yak-swc/yak_swc/src/utils/ast_helper.rs, packages/yak-swc/yak_swc/tests/fixture/cross-file-constants/input.tsx, packages/yak-swc/yak_swc/tests/fixture/cross-file-constants/output.tsx, packages/yak-swc/yak_swc/tests/fixture/cross-file-mixin-import/output.tsx
Member expressions with more than one level were handled incorrect.
```css
padding: ${layout.sidePaddings.val}
```
is turned into a doubled root ident
```css
padding: ${layout.layout.sidePaddings.val}
```
This change will fix that.
=> Fix nested member expressions

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/input.tsx, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/output.tsx
Almost all CSS Values are alphabetic:
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
But there is also `%`
This pr adds support for `%`
=> add support for % units

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/src/math_evaluate.rs, packages/yak-swc/yak_swc/src/variable_visitor.rs, packages/yak-swc/yak_swc/tests/fixture/constants/input.tsx, packages/yak-swc/yak_swc/tests/fixture/constants/output.tsx
This PR adds support for evaluating simple calculations in CSS template literals at build time, improving runtime performance while maintaining code readability.
- Added a new expression evaluator that handles:
- Basic arithmetic operations (+, -, *, /)
- Constant values
- Member expressions (e.g. `theme.spacing.lg * 2`)
- Parentheses for precedence control
- Integrated evaluation into the CSS template literal transformer
```jsx
// Input
const theme = {
spacing: {
base: 8,
lg: 16
}
};
const Container = styled.div`
/* Simple calculations */
width: ${300 / 2}px;
height: ${40 * 3}px;
/* With constants */
padding: ${theme.spacing.base * 2}px ${theme.spacing.lg * 1.5}px;
/* With parentheses */
margin: ${(theme.spacing.base + 4) * 2}px;
`;
// Output (after build)
const Container = styled.div` …
```
=> add Build-time Evaluation for CSS Calculations

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/tests/fixture/cross-file-mixin-import/output.tsx, packages/yak-swc/yak_swc/tests/fixture/cross-file-selectors/output.tsx
When using an imported mixin within a nested CSS rule, it was incorrectly being identified as a selector if there was a `{` character in the surrounding CSS context. For example:
```tsx
export const Button = styled.button`
&:hover {
${yakMixin};  // Was incorrectly marked as selector
}
`;
```
This caused the import to be encoded with `selector` instead of `mixin`:
```css
/* Before: Incorrect */
--yak-css-import: url("./constants.yak:yakMixin",selector);
/* After: Correct */
--yak-css-import: url("./constants.yak:yakMixin",mixin);
```
Updated the logic in `process_yak_literal` to look only at the code *after* the current expression when determining the import kind. This ensures that surrounding CSS context (like the `{` from `&:hover {`) doesn't interfere with the detection.
```rust
let …
```
=> fix incorrect selector/mixin import kind detection in nested CSS

packages/example/app/globals.css, packages/example/app/page.tsx
This PR adds examples demonstrating CSS [`@layer`](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer) support in next-yak, showcasing how layers can be used to manage style precedence and cascade in a more structured way
- Example: Added `@layer` declarations in global CSS
- Example: Implemented layered styles in a styled component
CSS `@layer` is a powerful addition to CSS that allows developers to explicitly manage the cascade and control specificity. When combined with next-yak, it offers several key benefits:
- Layers provide a way to control specificity without relying on selector specificity or `!important`
- The order of layer declarations determines their precedence, making style overrides more predictable
Example:
```tsx
@layer global, components, theme;
const Button = …
```
=> add layer example

packages/next-yak/runtime/__tests__/typeTest.tsx, packages/next-yak/runtime/styled.tsx
This fixes #180 
When we had the issue previously #104, I fixed it only for the case where the styled proxy was used on native elements. This PR adds the `NoInfer` also to the wrapping API of the styled function.
=> Add the NoInfer to the styled function

package.json, packages/cross-file-tests/__tests__/fixtures/constant/constants.ts, packages/cross-file-tests/__tests__/fixtures/constant/index.tsx, packages/cross-file-tests/__tests__/fixtures/constant/output/constants.ts, packages/cross-file-tests/__tests__/fixtures/constant/output/index.tsx, packages/cross-file-tests/__tests__/fixtures/constant/output/index.yak.module.css, packages/cross-file-tests/__tests__/fixtures/nestedMixin/output/helper/typography.tsx, packages/cross-file-tests/__tests__/fixtures/nestedMixin/output/mixin.tsx, packages/cross-file-tests/package.json, packages/next-yak/loaders/lib/resolveCrossFileSelectors.ts
Add support for negative numeric constants when importing from regular `.ts` files in styled components. Previously, trying to use negative numbers (like `-1`) from `.ts` files would fail during the static extraction phase with an "unexpected exportValue unsupported" error.
While `.yak.ts` files would handle negative numbers correctly through Node evaluation, the static extraction didn't support negative numbers, leading to confusing errors for users
- Added handling for UnaryExpression with negative numbers in the static extraction logic
- Enhanced error reporting by adding value hints when imports fail
- Added test cases for negative values
**Example Usage**
```typescript
// constants.ts
export const negative = -1;
// component.tsx
import { styled } from 'next-yak';
import { negative } …
```
=> fix support for negative numeric constants in cross-file imports

packages/yak-swc/yak_swc/src/utils/add_suffix_to_expr.rs, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/input.tsx, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/output.tsx
When using calculations with CSS units inside nested ``` css`` ``` literals, the unit is being multiplied as a string value which breaks the calculation. This only happens in nested ``` css`` ``` expressions, while direct styled-component expressions work correctly
```jsx
import { styled } from "next-yak";
// This works correctly ✅
export const FlexContainer = styled.div`
top: ${({ $top }) => $top * 20}%;
`;
```
Compiles correctly to:
```jsx
styled.div(__styleYak.FlexContainer, {
"style": {
"--FlexContainer__top_o1wkyu": __yak_unitPostFix(({ $top }) => $top * 20, "%")
}
});
```
```jsx
import { styled, css } from "next-yak";
// This breaks ❌
export const FlexContainer = styled.div`
${({ $bottom }) => css`bottom: ${$bottom * 20}%`};
`;
```
Compiles incorrectly to:
```jsx …
```
=> fix CSS unit handling in nested css`` expressions

packages/yak-swc/yak_swc/src/math_evaluate.rs, packages/yak-swc/yak_swc/tests/fixture/constants/input.tsx, packages/yak-swc/yak_swc/tests/fixture/constants/output.tsx
currently negative numbers in styled components were being converted to CSS variables and evaluated at runtime, even though they are constant values
This PR fixes this by inlining negative numbers directly into the CSS output
For example:
```tsx
const Button = styled.button`
margin-top: ${-1}px;
`;
```
Now correctly outputs:
```css
.Button_xyz {
margin-top: -1px;
}
```
Instead of using CSS variables and runtime evaluation
- Added test case in `constants/input.tsx` to verify negative number inlining
- All existing tests pass
Fixes #191
=> inline negative numbers

packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/tests/fixture/dynamic-prop-error/input.tsx, packages/yak-swc/yak_swc/tests/fixture/dynamic-prop-error/output.stderr, packages/yak-swc/yak_swc/tests/fixture/dynamic-prop-error/output.tsx
when migrating from styled-components, users often write dynamic values in CSS properties without realizing they'll be executed at runtime:
```javascript
import { styled } from "next-yak";
const Button = styled.button`
z-index: ${getZIndex()}
`
```
while this works (next-yak handles it by using CSS variables and inline styles), the runtime behavior isn't immediately obvious to users. 
This behaviour can lead to confusion about what gets extracted at build time versus what runs in the browser
Therefore this PR enforces the use of arrow functions for dynamic property values in top-level styled components. This makes the runtime nature of these values explicit in the syntax:
```javascript
import { styled } from "next-yak";
const Button = styled.button`
z-index: ${() => getZIndex()}
`
```
The …
=> enforce arrow functions

.changeset/early-falcons-clap.md, .github/workflows/changeset.yml, .github/workflows/node.js.yml, packages/example/app/__tests__/__snapshots__/Clock.test.tsx.snap, packages/example/app/__tests__/__snapshots__/ClockHands.test.tsx.snap, packages/yak-swc/yak_swc/src/naming_convention.rs, packages/yak-swc/yak_swc/src/utils/css_hash.rs, packages/yak-swc/yak_swc/tests/fixture/css-mixin-nested/output.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin/output.tsx, packages/yak-swc/yak_swc/tests/fixture/dynamic-prop-error/output.tsx, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/output.tsx, packages/yak-swc/yak_swc/tests/fixture/theming-with-context/output.tsx
This PR replaces our current CSS identifier hashing implementation with FNV-1a (Fowler-Noll-Vo), a fast and platform-independent hash function that is better suited for generating CSS identifiers.
- Replace custom hash implementation with FNV-1a algorithm
- Improve CSS identifier generation to ensure valid CSS class names
- Update tests with deterministic hash values
- Update snapshots to reflect new hash output format
The FNV-1a hash algorithm is an ideal choice for this use case because:
1. **Deterministic Output**: Guarantees consistent hashes across:
- Different operating systems (Windows/Mac/Linux)
- Different architectures (x86/ARM/WASM)
- Different builds and process executions
2. **Performance**: FNV-1a is:
- Simple and fast (uses basic bitwise operations)
- Memory efficient …
=> Switch to FNV-1a hash for CSS identifiers

.changeset/rich-hotels-shake.md, packages/next-yak/runtime/__tests__/typeTest.tsx, packages/next-yak/runtime/mocks/keyframes.ts
=> Allow primitive types in keyframes

.changeset/wild-pants-report.md, packages/next-yak/runtime/__tests__/typeTest.tsx, packages/next-yak/runtime/cssLiteral.tsx, packages/next-yak/runtime/mocks/cssLiteral.ts, packages/next-yak/runtime/styled.tsx
=> Don't infer types of selectors in mixins

.changeset/silver-hairs-clean.md, packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/src/naming_convention.rs
I've added support for configuring the prefix used by next-yak for generated CSS classes and variables  
This can help in identifying yak-generated classes in tests or to avoid collisions with other libraries
The default prefix remains `y` in production and empty in dev mode, so this is fully backwards compatible
If needed you can now configure a custom prefix:
```js
// next.config.js
export default withYak({
prefix: 'my-app-'
});
```
The patch also adjusts the dev mode variable prefix from 'yak_' to 'var_' which makes a bit more sense semantically
=> allow to define the prefix for generated names

.changeset/angry-dingos-remain.md, packages/next-yak/runtime/__tests__/cssPropTest.tsx, packages/next-yak/runtime/styled.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop/input.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop/output.prod.tsx
This was noticed in #240 
This change alters the public API of styled components e.g. `styled.div` or `styled.p` to accept an optional CSS property the same way as native elements do with our JSX definition.
This works now without a type error:
```tsx
const Text = styled.p`
font-size: 20px;
font-weight: bold;
font-family: "Inter";
`;
<Text
css={css`
color: red;
`}
>
test
</Text>
```
=> Enable css props on styled components

.changeset/flat-bulldogs-attend.md, packages/example/app/page.tsx, packages/yak-swc/yak_swc/src/yak_transforms.rs, packages/yak-swc/yak_swc/tests/fixture/css-prop-nested/input.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop-nested/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop-nested/output.prod.tsx
This issue was raised here: https://github.com/jantimon/next-yak/issues/240#issuecomment-2550709575
This PR fixes the assigned class names for css props in nested JSX structures.
```jsx
<div
css={css`
color: red;
`}
>
<p
css={css`
color: blue;
`}
>
<span
css={css`
color: green;
}`}
>
hello
</span>
world
</p>
</div>
```
produced this:
```diff
<div {.../*YAK Extracted CSS:
.yak {
color: red;
}
*/ /*#__PURE__*/ css(__styleYak.yak)({})}>
<p {.../*YAK Extracted CSS:
.yak-01 {
color: blue;
}
-*/ /*#__PURE__*/ css(__styleYak.yak)({})}>
+*/ /*#__PURE__*/ css(__styleYak["yak-01"])({})}>
<span {.../*YAK Extracted CSS:
.yak-02 {
color: green;
}
-*/ /*#__PURE__*/ css(__styleYak.yak)({})}>
+*/ /*#__PURE__*/ css(__styleYak["yak-02"])({})}>
hello
</span>
world
</p>
</div>;
```
=> Fix nested css prop

.changeset/selfish-hotels-travel.md, packages/next-yak/runtime/styled.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
Closes #248
Updated `@types/react` to `19.0.2` and removed our own `FunctionComponent` as the new `React.FunctionComponent` is now almost the same.
=> Update react types to 19.0.2

.changeset/smart-cars-eat.md, packages/next-yak/runtime/__tests__/cssPropTest.tsx, packages/next-yak/runtime/__tests__/typeTest.tsx, packages/next-yak/runtime/cssLiteral.tsx, packages/next-yak/runtime/index.ts, packages/next-yak/runtime/jsx-runtime.ts, packages/next-yak/runtime/mocks/cssLiteral.ts, packages/next-yak/runtime/styled.tsx
Fixes #256
- Unifies static CSS prop and dynamic CSS mixin types.
- Exports a new type `CSSProp` that can be used by custom components to receive the css prop in a somewhat typesafe manner
usage: 
```tsx
const MyDivProps = ComponentProps<"div">;
const MyComponent: FunctionComponent<MyDivProps & CSSProp> = (props) =>
<div {...p}>This spreading works</div>;
```
=> Unify type of static css prop and dynamic css mixin

.changeset/new-news-smile.md, .github/workflows/codspeed.yml, .github/workflows/docs.yml, .github/workflows/example.yml, .github/workflows/node.js.yml, CONTRIBUTION.md, packages/docs/app/api/transform/route.ts, packages/docs/next.config.mjs, packages/yak-swc/package.json, packages/yak-swc/yak_swc/.cargo/config
Update deprecated `wasm-wasi` target to `wasm-wasip1`
> warning: the `wasm32-wasi` target is being renamed to `wasm32-wasip1` and the `wasm32-wasi` target will be removed from nightly in October 2024 and removed from stable Rust in January 2025
=> Update wasm target

LICENSE
The license is specified in the README.md, which is legally sufficient (afaik), but it's not automatically picked up by github and thus not shown as a repository property.
This can be fixed by adding a `LICENSE.md`
=> Add `LICENSE.md`

.changeset/gentle-dragons-count.md, packages/next-yak/loaders/css-loader.ts, packages/next-yak/loaders/lib/resolveCrossFileSelectors.ts, packages/next-yak/package.json, packages/next-yak/tsup.config.ts, packages/next-yak/withYak/index.ts
After migrating more and more styled-components usages to next-yak, we started to experience failed nextjs builds (next build). The build ended without any error message and with a success status code, which is quite strange. After some time analyzing the issue, we were able to relate the issue to the parsed files cache within the css-loader.
Initially, the cache stored the promise resolving and parsing a module and its dependencies. A parallel request resolving the same module would, therefore, await the same promise and not load the module again. This likely led to a deadlock, or it has just exceeded the maximum number of concurrent loader executions.
Removing the cache solved the issue but slowed the build down quite a bit. With this PR, we change the cache to only cache the final …
=> Improve css-loader cache to avoid failing build with nextjs and webpack

.changeset/giant-bobcats-sleep.md, packages/yak-swc/yak_swc/src/utils/add_suffix_to_expr.rs, packages/yak-swc/yak_swc/tests/fixture/css-mixin-nested/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin-nested/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/dynamic-prop-error/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/dynamic-prop-error/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/nested-dynamic-mixin/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/nested-dynamic-mixin/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/parens/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/parens/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/props-and-dynamic-styles/output.prod.tsx
Uses the magic [PURE_SP](https://docs.rs/swc_common/latest/swc_common/source_map/constant.PURE_SP.html) span to mark the call to `__yak_unitPostFix` as
pure. Swc code-gen will inject a `/* #__PURE__ */` comment when it sees the byte offset of that span.
That way, more code for unused components can be
removed by the usual dead code analysis.
Fixes #228
=> Mark __yak_unitPostFix as pure

.changeset/thirty-badgers-wait.md, packages/cross-file-tests/__tests__/fixtures/sameFileMixin/output/index.tsx, packages/cross-file-tests/__tests__/fixtures/sameFileMixin/output/index.yak.module.css, packages/yak-swc/yak_swc/src/naming_convention.rs, packages/yak-swc/yak_swc/src/yak_transforms.rs, packages/yak-swc/yak_swc/tests/fixture/cross-file-mixin-dynamic-export/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin-inline/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin-nested/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-mixin/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-object/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/nested-dynamic-mixin/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/parens/output.dev.tsx
This PR addresses CSS class name escaping issues that caused rendering problems in development mode. 
The implementation now correctly handles special characters like `$`, `[`, `]` and emoji by preserving them in HTML class attributes while properly escaping them in CSS selectors
=> fix-class-name-escaping

.changeset/fair-shoes-hope.md, packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-function/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-object/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/keyframe-animations-object/output.prod.tsx
This PR addresses an issue where keyframe animations would not work properly when referenced in an animation property before the keyframe was declared in the code. 
When keyframes were referenced before their declaration, the animation reference in the CSS wasn't properly wrapped with `:global()`, causing CSS modules to generate different names for the animation reference and the keyframe declaration. This resulted in broken animations in the compiled output.
For example:
```css
/* What was happening */
.Component {
animation: animationName_i9blVg 1s ease; /* Missing :global() wrapper */
}
@keyframes :global(animationName_i9blVg) {
from { opacity: 0; }
to { opacity: 1; }
}
```
This pr modified the Rust code to ensure that keyframe references are properly wrapped with `:global()` even when …
=> Fix keyframe animation references when used before declaration 

.changeset/short-spoons-punch.md, packages/yak-swc/css_in_js_parser/src/to_css.rs
This PR addresses issue #325 where CSS Houdini's `@property` rules were not working correctly when nested inside selectors. According to CSS specs, `@property` rules must appear at the top level of a stylesheet to function properly.
The fix **modifies the CSS stringification** to identify `@property` rules and hoist them to the root level, maintaining compatibility with other CSS processors like Emotion/styled-components that automatically handle this hoisting.
**Testing**: Added test case to verify `@property` hoisting behavior.
Fixes #325
=> Hoist @property rules to root level

packages/docs/components/errorBoundary.tsx, packages/docs/components/landingPage.tsx
This PR adds an `<ErrorBoundary>` for `shiki-magic-move` in safari:
=> Add error boundary for shiki-magic-move in safari

packages/docs/lib/shiki.ts
From the [shiki docs](https://shiki.style/guide/regex-engines#use-with-unsupported-languages):
> Unlike the Oniguruma engine, the JavaScript engine is strict by default. It will throw an error if it encounters an invalid Oniguruma pattern or a pattern that it cannot convert. If you want best-effort results for unsupported grammars, you can enable the forgiving option to suppress any conversion errors.
This enables `forgiving` mode for our highlighter to work in safari.
Preview: https://next-yak-docs-77rr3m2km-jan-nicklas-projects.vercel.app/
=> Set regexp engine to forgiving for safari

.changeset/cold-humans-matter.md, packages/next-yak/loaders/lib/resolveCrossFileSelectors.ts, packages/next-yak/package.json, packages/next-yak/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
Use `@babel/parser` and `@babel/traverse` directly in order to rely on web friendly API's (to be used in the playground).
This change should decrease our package size as `@babel/core` has the others as dependencies:
=> Optimize babel usage for web

.changeset/fine-numbers-repair.md, packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/src/variable_visitor.rs, packages/yak-swc/yak_swc/tests/fixture/constants/input.tsx, packages/yak-swc/yak_swc/tests/fixture/constants/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/constants/output.prod.tsx
This closes #368 
It adds support for more access patterns of constant objects like string and number literals.
Example:
```tsx
const styles = {
small: "20px",
"extra-small": "16px",
1: "12px",
};
const Component = styled.div`
margin: {styles.small}; // This works already
padding: {styles['extra-small']}; // Support for this was added
font-size: {styles[1]}; // Support for this was added
`;
```
=> Support more access patterns for same file constant replacement

.changeset/afraid-socks-own.md, packages/yak-swc/yak_swc/src/lib.rs, packages/yak-swc/yak_swc/src/utils/css_prop.rs, packages/yak-swc/yak_swc/tests/fixture/css-prop-invalid/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop-invalid/output.prod.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop-invalid/output.stderr, packages/yak-swc/yak_swc/tests/fixture/css-prop-with-atoms-simple/input.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop-with-atoms-simple/output.dev.tsx, packages/yak-swc/yak_swc/tests/fixture/css-prop-with-atoms-simple/output.prod.tsx
This fixes the issue `ReferenceError: __yak_mergeCssProp is not defined` when using `atoms` without any other CSS we provide (`css` or `styled`).
We know add the import to our internals when using any yak import, instead of only adding it when a CSS extraction is needed.
=> Fix reference error when only using atoms

.changeset/little-planets-clean.md, .github/workflows/autofix.yml, .github/workflows/changeset.yml, .github/workflows/codspeed.yml, .github/workflows/docs.yml, .github/workflows/example.yml, .github/workflows/node.js.yml, .github/workflows/release.yml, package.json, packages/docs/app/(home)/playground/page.tsx, packages/docs/components/editor.tsx, packages/example/app/Input.tsx, packages/example/app/__tests__/__snapshots__/Clock.test.tsx.snap, packages/example/app/__tests__/__snapshots__/ClockHands.test.tsx.snap, packages/example/next-env.d.ts, pnpm-lock.yaml, pnpm-workspace.yaml
This updates all dependencies to the latest version.
Additionally I've updated PNPM to the latest version `10.15.0` and Node to `22`, but unfortunately because of the `pull_request_target` event, the workflows still take the "old" version that resides on master. I've run them manually here:
- [Docs](https://github.com/DigitecGalaxus/next-yak/actions/runs/17342749011/job/49238809797)
- [Example](https://github.com/DigitecGalaxus/next-yak/actions/runs/17342810451)
=> Update all dependencies
